development:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
test:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
subouttest:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq
production:
  recaptcha:
    public_key: 6LdFoAQTAAAAAA28FgNB_PYKvoM7kJao5IpbPp3I
    private_key: 6LdFoAQTAAAAAOBIJlIbT23uKuZGcTfyxsRCcitq